package com.sqooid.fheart.ui

object BluetoothIds {
    val BATTERY_SERVICE = "180f"
    val DEVICE_INFORMATION_SERVICE = "180a"
    val GAP_SERVICE = "1800"
    val GATT_SERVICE = "1801"
    val HEART_RATE_SERVICE = "180d"

    val HEART_RATE_MEASUREMENT_CHAR = "2a37"
    val BATTERY_LEVEL_CHAR = "2a37"
    val MANUFACTURER_NAME_STRING_CHAR = "2a29"
    val MODEL_NUMBER_STRING_CHAR = "2a24"
    val SERIAL_NUMBER_STRING_CHAR = "2a25"
    val HARDWARE_REVISION_STRING_CHAR = "2a27"
    val FIRMWARE_REVISION_STRING_CHAR = "2a26"
    val SOFTWARE_REVISION_STRING_CHAR = "2a28"
}

fun getLongId(id:String):String {
    return "0000${id}-0000-1000-8000-00805F9B34FB"
}
